### ISSUE TITLE
Multiple contexts example doesn't validate.

### ISSUE THREAD

**Issue by jonathancrabtree** [datatagsuite/dats-tools#3]
The multiple context files example given here doesn't appear to validate:

https://github.com/datatagsuite/dats-tools/blob/master/notebooks/dats_multiple_contexts.ipynb

The following errors are generated by the validator in dats-tools:

[0, 'type'] ['https://datatagsuite.github.io/context/sdo/dataset_sdo_context.jsonld', 'https://datatagsuite.github.io/context/obo/dataset_obo_context.jsonld'] is not of type 'string'
[1, 'type'] ['https://datatagsuite.github.io/context/sdo/dataset_sdo_context.jsonld', 'https://datatagsuite.github.io/context/obo/dataset_obo_context.jsonld'] is not of type 'object'

The context definition of the top-level Dataset looks like this (replacing ampersands with "[ampersand]"):

"""
"[ampersand]context": [ "https://w3id.org/dats/context/sdo/dataset_sdo_context.jsonld", "https://w3id.org/dats/context/obo/dataset_obo_context.jsonld"],
"""

But in https://github.com/datatagsuite/schema/blob/master/dataset_schema.json the context is defined as follows:

"""
        "[ampersand]context": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "type": "object"
                }
            ]
        },
"""

The provided list is neither a string nor an object. It seems like allowing multiple contexts using the list syntax is going to require changing each and every DATS schema to allow the context to be a string, an object, or a list of (string or object). In addition, it's not clear to me whether the schema needs to annotate the list as an _ordered_  JSON-LD list, since the order of context files in the list is clearly significant. (Whether the various parsers, including rdflib, would pay any attention to this is another question. rdflib seems perfectly happy to accept lists of context files even though the DATS schema doesn't currently allow them.)

**Comment by agbeltran** [comment]
Thanks - extended the schemas to address this issue (see https://github.com/datatagsuite/schema/commit/15296a1dbedacd37fdda138d88ff38f2bf7e106f)
